FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go mod tidy


# Stage 2: Runner
FROM alpine:latest

# Install sertifikat SSL (Wajib untuk Firebase)
RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy binary dari stage builder
COPY --from=builder /app/backend-api .

EXPOSE 8000

CMD ["./backend-api"]
